Fpvalue <- function(modelobject) {
  # p-value of overall-F of regression
  # Adoped, 2022-01-04
  #
  # modelobject [special]: must have been generated by R function lm, and computed  by
  # statement such as ModelObkect<lm(y~X) 
  #
  # Returns 1x1 vector of p-value of F
  # Why? Because the "summary" of lm object lists but does not store this p-value
  #
  # Source of function
  # https://stackoverflow.com/questions/5587676/pull-out-p-values-and-r-squared-from-a-linear-regression
 
  if (class(modelobject) != "lm") stop("Not an object of class 'lm' ")
  f <- summary(modelobject)$fstatistic
  p <- pf(f[1],f[2],f[3],lower.tail=F)
  attributes(p) <- NULL
  return(p)
}


